name: rdvenv
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - kaggle
    - pandas
    - numpy
    - pip
    - pip:
          - seaborn
          - matplotlib
          - psycopg2
          - pyspark
