name: rdvenv
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - kaggle
    - pandas
    - numpy
    - pip
    - pip:
          - findspark
          - python-dotenv
          - seaborn
          - matplotlib
          - psycopg2
          - pyspark
          - requests
          - pycouchdb
          - kafka-python
          - "apache-airflow[celery]==3.0.1"
