name: rdvenv
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - kaggle
    - pandas
    - numpy
    - pip
    - pip:
          - urllib3>=2
          - boto3
          - r2client
          - findspark
          - pyarrow
          - python-dotenv
          - seaborn
          - matplotlib
          #   - psycopg2
          - requests
          - pycouchdb
          - couchdb
          - kafka-python
          - "apache-airflow[celery]==3.0.1"
          - prophet
          - streamlit
          - plotly
