---
services:
    # COUCHDB
    couchdb:
        image: couchdb:latest
        container_name: group1
        restart: always
        networks:
            - proxy
        ports:
            - 5984:5984
        volumes:
            - couchdb_data:/opt/couchdb/data
            - couchdb_config:/opt/couchdb/etc/local.d
            - couchdb_log:/opt/couchdb/var/log
        environment:
            COUCHDB_USER: ${APP_USER}
            COUCHDB_PASSWORD: ${APP_PASSWORD}
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 128M

    # KAFKA
    controller-1:
        image: apache/kafka:latest
        container_name: controller-1
        volumes:
            - ./kafka_controller_data/controller-1:/tmp/kafka-logs
        networks:
            - proxy
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: controller
            KAFKA_LISTENERS: CONTROLLER://:9093
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LOG_DIRS: /tmp/kafka-logs
            KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 160M

    broker-1:
        image: apache/kafka:latest
        container_name: broker-1
        volumes:
            - ./kafka_broker_data/broker-1:/tmp/kafka-logs
        networks:
            - proxy
        ports:
            - 29092:9092
        environment:
            KAFKA_NODE_ID: 2
            KAFKA_PROCESS_ROLES: broker
            KAFKA_LISTENERS: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://10.34.100.114:29092"
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LOG_DIRS: /tmp/kafka-logs
            KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"
        depends_on:
            - controller-1
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 300M

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        networks:
            - proxy
        ports:
            - "3030:8080"
        depends_on:
            - broker-1
        environment:
            KAFKA_CLUSTERS_0_NAME: broker-1
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-1:19092
            JAVA_OPTS: "-Xms128m -Xmx128m"
        deploy:
            resources:
                limits:
                    memory: 192M
                reservations:
                    memory: 160M

volumes:
    couchdb_data:
        external: true
    couchdb_config:
        external: true
    couchdb_log:
        external: true
    # kafka_controller_data:
    # kafka_broker_data:

networks:
    proxy:
        name: proxy
