---
services:
    etl-fw:
        image: weather-kafka-etl:1.0
        container_name: etl-fw
        networks:
            - proxy
        environment:
            APP_USER: ${APP_USER}
            APP_PASSWORD: ${APP_PASSWORD}
            COUCHDB_HOST: group1
            COUCHDB_PORT: 5984
            KAFKA_BOOTSTRAP_SERVERS: broker-1:19092
        restart: unless-stopped

networks:
    proxy:
        name: proxy
        external: true
